In [2]:
import numpy as np

### Pricing a 1-year quarterly-pay plain vanilla swap 
Day count convention is 30/360.
The quaterly floating interest rate is 2.5%, 3%, 3.5%, 4%.

In [20]:
#Example 1
#pricing a 1-year quarterly-pay plain vanilla swap using 30/360
rates=np.arange(.025,.045,.005)
print(rates)
times=np.arange(90,450,90)
print(times)
def discfactor(rates,times):
    return 1/(1+rates*times/360)
print(discfactor(rates, times))

discount_factor1=discfactor(.025,90)
discount_factor2=discfactor(.03,180)
discount_factor3=discfactor(.035,270)
discount_factor4=discfactor(.04,360)
print("The discount factor for 1st quater is {0:.4f}.".format(discount_factor1))
print("The discount factor for 2nd quater is {0:.4f}.".format(discount_factor2))
print("The discount factor for 3th quater is {0:.4f}.".format(discount_factor3))
print("The discount factor for 4th quater is {0:.4f}.".format(discount_factor4))


[0.025 0.03  0.035 0.04 ]
[ 90 180 270 360]
[0.99378882 0.98522167 0.97442144 0.96153846]
The discount factor for 1st quater is 0.9938.
The discount factor for 2nd quater is 0.9852.
The discount factor for 3th quater is 0.9744.
The discount factor for 4th quater is 0.9615.


In [21]:
def coupon_rate(discount_factor1,discount_factor2,discount_factor3,discount_factor4):
    sum=discount_factor1+discount_factor2+discount_factor3+discount_factor4
    return(1-discount_factor4)/sum
coupon_rate=coupon_rate(discount_factor1,discount_factor2,discount_factor3,discount_factor4)
print("The coupon rate is {0:.2f}%".format(coupon_rate*100))
swap_rate=coupon_rate*4
print("The swap rate is {0:.2f}%".format(swap_rate*100))

The coupon rate is 0.98%
The swap rate is 3.93%


### Valation of a pay-fixed interest rate swap
The swap rate of a 1-year quarterly-pay plain vanilla swap is 3.92% and the notional principal is $1000.
The Libor spot rate at beginning :R(90-days)=2.5%.
Assume after 30 days the Libor spot rates are: R(60-day)=3%;R(150-day)=3.5%;R(240-day)=4%; R(330-day)=4.5%. Calculate the value of this swap to the pay-fixed side after 30 days. 


In [22]:
#Example 2
#valation of a pay-fixed interest rate swap
fixed_rate=0.0392
float_rate=0.025

notional=1000
r60=0.03
r150=0.035
r240=0.04
r330=0.045

In [23]:
def discount_factor(rate,time):
    return 1/(1+rate*time/360)

df60=discount_factor(r60,60)
df150=discount_factor(r150,150)
df240=discount_factor(r240,240)
df330=discount_factor(r330,330)

In [24]:
DFS=np.array([df60,df150,df240,df330])
print(DFS)

[0.99502488 0.98562628 0.97402597 0.96038415]


In [25]:
cf=notional*fixed_rate/4
cashflows=np.array([cf,cf,cf,cf+notional])
print(cashflows)

[   9.8    9.8    9.8 1009.8]


In [26]:
fixed_pv=DFS*cashflows
print(fixed_pv)
fixed_value=np.sum(fixed_pv)
print('The present value of fixed leg is {0:.2f}'.format(fixed_value))

[  9.75124378   9.65913758   9.54545455 969.79591837]
The present value of fixed leg is 998.75


In [27]:
float_value=notional*(1+float_rate/4)*df60
print(float_value)

1001.2437810945277


In [28]:
IRS_value=float_value-fixed_value
print('The swap value is {0:.2f}'.format(IRS_value))

The swap value is 2.49
